run:
    tests: false
linters:
    disable-all: true
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - dupl
        - funlen
        - goconst
        - gocyclo
        - gocritic
        - goimports
        - goprintffuncname
        - gosec
        - lll
        - misspell
        - nakedret
        - prealloc
        - unconvert
        - unparam
        - godox
