# This circleci config file will run tests 
version: 2.1

# jobs
jobs:
  #Run Linter  
  lint:
    docker:
      - image: cimg/go:1.22.1
    steps:
      - checkout # check out source code to working directory

      #Run Test
      - run: 
          name: "Run Linter"
          command: |
            golangci-lint run  ./...
  #Run Test  
  test:
    docker:
      - image: cimg/go:1.22.1
    steps:
      - checkout # check out source code to working directory

      #Run Test
      - run: 
          name: "Run Test"
          command: |
            go test -v -race ./...
  
# work flows
workflows:
  version: 2
  # build binary
  build:
    jobs:
      - lint
      - test